/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import windows.Level2;

/**
 *
 * @author imartinb04
 */
public class MainWindow extends javax.swing.JFrame
{
    private static byte cont_lvl_x = 0;
    public String[] score_info = new String[4];
    
    public MainWindow()
    {
        initComponents();
        
        this.getContentPane().setBackground(new Color(0x3C3F41));
        this.score_table.setBackground(new Color(0x3C3F41));
        this.score_table.setForeground(Color.decode("#FCE7FC"));
        this.lvl1.setBackground(Color.black);
        this.lvl2.setBackground(Color.black);
        this.lvlX.setBackground(Color.black);
        
        // Ssssh, it's a secret, boyo
        this.lvlX.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        score_table = new javax.swing.JTable();
        lvl1 = new javax.swing.JButton();
        lvl2 = new javax.swing.JButton();
        lvlX = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        score_table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.darkGray, java.awt.Color.green, java.awt.Color.darkGray, java.awt.Color.green));
        score_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Name", "Level", "Time", "Score"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        score_table.setOpaque(false);
        jScrollPane1.setViewportView(score_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 900, 290));

        lvl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/level1.png"))); // NOI18N
        lvl1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lvl1ActionPerformed(evt);
            }
        });
        getContentPane().add(lvl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 100, 30));

        lvl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/level2.png"))); // NOI18N
        lvl2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lvl2ActionPerformed(evt);
            }
        });
        getContentPane().add(lvl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 100, 30));

        lvlX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/levelX.png"))); // NOI18N
        lvlX.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lvlXActionPerformed(evt);
            }
        });
        getContentPane().add(lvlX, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 100, 30));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hiddengem.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setScore()
    {
        DefaultTableModel dts = (DefaultTableModel) this.score_table.getModel();
        dts.addRow(score_info);
        
        // Se modifica el contador por nivel finalizado
        cont_lvl_x++;
        
        // Pah mostrar el botón del Nivel Secreto
        if(cont_lvl_x == 2)
        {
            this.lvlX.setVisible(true);
            this.repaint();
        }
    }
    
    
    private void lvl1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lvl1ActionPerformed
    {//GEN-HEADEREND:event_lvl1ActionPerformed
        Level1 lvl1 = new Level1(this, true);
        
        lvl1.setVisible(true);
    }//GEN-LAST:event_lvl1ActionPerformed

    private void lvlXActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lvlXActionPerformed
    {//GEN-HEADEREND:event_lvlXActionPerformed
        LevelX lvlx = new LevelX(this, true);
        
        lvlx.setVisible(true);
    }//GEN-LAST:event_lvlXActionPerformed

    private void lvl2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lvl2ActionPerformed
    {//GEN-HEADEREND:event_lvl2ActionPerformed
        Level2 lvl2 = new Level2(this, true);
        
        lvl2.setVisible(true);
    }//GEN-LAST:event_lvl2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton lvl1;
    private javax.swing.JButton lvl2;
    private javax.swing.JButton lvlX;
    private javax.swing.JTable score_table;
    // End of variables declaration//GEN-END:variables
}
