/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package windows;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import windows.Level2;
/**
 *
 * @author imartinb04
 */
public class YouWin extends javax.swing.JDialog
{

    private MainWindow main_win;
    
    public YouWin(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        
        this.getContentPane().setBackground(Color.BLACK);
        
        // Inicializa la variable principal con la ventana principal
        this.main_win = (MainWindow) parent;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Continue = new javax.swing.JButton();
        YouWin_Label = new javax.swing.JLabel();
        name_Field = new javax.swing.JTextField();
        enter_name_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Continue.setBackground(new java.awt.Color(168, 235, 185));
        Continue.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        Continue.setForeground(new java.awt.Color(0, 0, 0));
        Continue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/continue.gif"))); // NOI18N
        Continue.setText("𝕣𝕖𝕤𝕥𝕒𝕣𝕥");
        Continue.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ContinueActionPerformed(evt);
            }
        });

        YouWin_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/youwin.png"))); // NOI18N

        name_Field.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        name_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name_Field.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        name_Field.setSelectionColor(new java.awt.Color(153, 255, 153));
        name_Field.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                name_FieldActionPerformed(evt);
            }
        });

        enter_name_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/entername_2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_Field)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(YouWin_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34)
                        .addComponent(Continue, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(enter_name_Label)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(YouWin_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Continue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enter_name_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ContinueActionPerformed
    {//GEN-HEADEREND:event_ContinueActionPerformed
        String name = this.name_Field.getText();
        
        if(name_Field.getText().isEmpty())
        {
            // Si no se pone un nombre en el text field se le asigna uno
            main_win.score_info[0] = "Very Mysterious Person";
        }
        else
        {
            main_win.score_info[0] = name;
        }
        
        
        // Añadimos el array al score board
        main_win.setScore();
        
        dispose();
    }//GEN-LAST:event_ContinueActionPerformed

    private void name_FieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_name_FieldActionPerformed
    {//GEN-HEADEREND:event_name_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_FieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(YouWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(YouWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(YouWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(YouWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
    {
                YouWin dialog = new YouWin(new javax.swing.JFrame(), true); // Pasa la instancia de Level1 actual
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Continue;
    private javax.swing.JLabel YouWin_Label;
    private javax.swing.JLabel enter_name_Label;
    private javax.swing.JTextField name_Field;
    // End of variables declaration//GEN-END:variables
}
